-- TRACE Seed Data — Demo accounts and sample case
-- Passwords are bcrypt hashes generated by passlib (verified against the
-- plaintext passwords documented below and in the README).
-- ⚠️  CHANGE THESE CREDENTIALS IN PRODUCTION

-- Admin account: admin@trace.dev / TraceAdmin123!
-- Investigator account: investigator@trace.dev / TraceInvestigator123!
-- (.dev is used because EmailStr/email-validator rejects reserved domains like .local)

INSERT INTO users (id, email, password_hash, full_name, role, is_active) VALUES
    ('a0000000-0000-0000-0000-000000000001', 'admin@trace.dev',
     '$2b$12$2j8teowF.nKUG77AnZvrIeVWMcN1L.ZhojM6lmKqw3SQMlj2HGCAa',
     'System Administrator', 'admin', true),
    ('a0000000-0000-0000-0000-000000000002', 'investigator@trace.dev',
     '$2b$12$KQ4h5nR3NKrh7m0lopLa0OgY9TChRJh6HlN8zLysdv7y0o4qNVWYu',
     'Demo Investigator', 'investigator', true);

-- Demo case
INSERT INTO cases (id, name, description, created_by, status) VALUES
    ('c0000000-0000-0000-0000-000000000001', 'Operation Nexus',
     'Training exercise on a fictional financial network involving shell companies and layered fund transfers across multiple accounts.',
     'a0000000-0000-0000-0000-000000000001', 'open');

-- Assign both users to the demo case
INSERT INTO case_assignments (case_id, user_id) VALUES
    ('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000001'),
    ('c0000000-0000-0000-0000-000000000001', 'a0000000-0000-0000-0000-000000000002');

-- Seed audit log entry
INSERT INTO audit_log (user_id, action, target_type, target_id, metadata) VALUES
    ('a0000000-0000-0000-0000-000000000001', 'SYSTEM_SEED', 'system', 'seed',
     '{"message": "Database seeded with demo accounts and sample case"}');
